package com.nabssam.bestbook.presentation.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF223876)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFFFFF)
val onPrimaryContainerLight = Color(0xFF11144B)
val secondaryLight = Color(0xFF5C5D72)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFFFFF)
val onSecondaryContainerLight = Color(0xFF191A2C)
val tertiaryLight = Color(0xFF78536A)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFFFFF)
val onTertiaryContainerLight = Color(0xFF2E1126)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFFFFFF)
val onBackgroundLight = Color(0xFF1B1B21)
val surfaceLight = Color(0xFFFFFFFF)
val onSurfaceLight = Color(0xFF1B1B21)
val surfaceVariantLight = Color(0xFFFFFFFF)
val onSurfaceVariantLight = Color(0xFF46464F)
val outlineLight = Color(0xFF777680)
val outlineVariantLight = Color(0xFFC7C5D0)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF303036)
val inverseOnSurfaceLight = Color(0xFFFFFFFF)
val inversePrimaryLight = Color(0xFFFFFFFF)
val surfaceDimLight = Color(0xFFFFFFFF)
val surfaceBrightLight = Color(0xFFFFFFFF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFFFFFF)
val surfaceContainerLight = Color(0xFFFFFFFF)
val surfaceContainerHighLight = Color(0xFFFFFFFF)
val surfaceContainerHighestLight = Color(0xFFFFFFFF)

val primaryDark = Color(0xFFBFC2FF)
val onPrimaryDark = Color(0xFF272B60)
val primaryContainerDark = Color(0xFF3E4278)
val onPrimaryContainerDark = Color(0xFFE0E0FF)
val secondaryDark = Color(0xFFC5C4DD)
val onSecondaryDark = Color(0xFF2E2F42)
val secondaryContainerDark = Color(0xFF444559)
val onSecondaryContainerDark = Color(0xFFE1E0F9)
val tertiaryDark = Color(0xFFE8B9D4)
val onTertiaryDark = Color(0xFF46263B)
val tertiaryContainerDark = Color(0xFF5E3C52)
val onTertiaryContainerDark = Color(0xFFFFD8ED)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF131318)
val onBackgroundDark = Color(0xFFE4E1E9)
val surfaceDark = Color(0xFF131318)
val onSurfaceDark = Color(0xFFE4E1E9)
val surfaceVariantDark = Color(0xFF46464F)
val onSurfaceVariantDark = Color(0xFFC7C5D0)
val outlineDark = Color(0xFF918F9A)
val outlineVariantDark = Color(0xFF46464F)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE4E1E9)
val inverseOnSurfaceDark = Color(0xFF303036)
val inversePrimaryDark = Color(0xFF565992)
val surfaceDimDark = Color(0xFF131318)
val surfaceBrightDark = Color(0xFF39393F)
val surfaceContainerLowestDark = Color(0xFF0E0E13)
val surfaceContainerLowDark = Color(0xFF1B1B21)
val surfaceContainerDark = Color(0xFF1F1F25)
val surfaceContainerHighDark = Color(0xFF2A292F)
val surfaceContainerHighestDark = Color(0xFF35343A)

val Purple80 = Color(0xFFD0BCFF)
val BoxColor = Color(0xfff3f3f3)
val Star = Color(0xFFFF9800)
val GreenColor=Color(0xFF4CAF50)



/*
package com.nabssam.bestbook.presentation.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF565992)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFE0E0FF)
val onPrimaryContainerLight = Color(0xFF11144B)
val secondaryLight = Color(0xFF5C5D72)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFE1E0F9)
val onSecondaryContainerLight = Color(0xFF191A2C)
val tertiaryLight = Color(0xFF78536A)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFD8ED)
val onTertiaryContainerLight = Color(0xFF2E1126)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFBF8FF)
val onBackgroundLight = Color(0xFF1B1B21)
val surfaceLight = Color(0xFFFBF8FF)
val onSurfaceLight = Color(0xFF1B1B21)
val surfaceVariantLight = Color(0xFFE4E1EC)
val onSurfaceVariantLight = Color(0xFF46464F)
val outlineLight = Color(0xFF777680)
val outlineVariantLight = Color(0xFFC7C5D0)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF303036)
val inverseOnSurfaceLight = Color(0xFFF3EFF7)
val inversePrimaryLight = Color(0xFFBFC2FF)
val surfaceDimLight = Color(0xFFDCD9E0)
val surfaceBrightLight = Color(0xFFFBF8FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF5F2FA)
val surfaceContainerLight = Color(0xFFF0ECF4)
val surfaceContainerHighLight = Color(0xFFEAE7EF)
val surfaceContainerHighestLight = Color(0xFFE4E1E9)

val primaryDark = Color(0xFFBFC2FF)
val onPrimaryDark = Color(0xFF272B60)
val primaryContainerDark = Color(0xFF3E4278)
val onPrimaryContainerDark = Color(0xFFE0E0FF)
val secondaryDark = Color(0xFFC5C4DD)
val onSecondaryDark = Color(0xFF2E2F42)
val secondaryContainerDark = Color(0xFF444559)
val onSecondaryContainerDark = Color(0xFFE1E0F9)
val tertiaryDark = Color(0xFFE8B9D4)
val onTertiaryDark = Color(0xFF46263B)
val tertiaryContainerDark = Color(0xFF5E3C52)
val onTertiaryContainerDark = Color(0xFFFFD8ED)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF131318)
val onBackgroundDark = Color(0xFFE4E1E9)
val surfaceDark = Color(0xFF131318)
val onSurfaceDark = Color(0xFFE4E1E9)
val surfaceVariantDark = Color(0xFF46464F)
val onSurfaceVariantDark = Color(0xFFC7C5D0)
val outlineDark = Color(0xFF918F9A)
val outlineVariantDark = Color(0xFF46464F)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE4E1E9)
val inverseOnSurfaceDark = Color(0xFF303036)
val inversePrimaryDark = Color(0xFF565992)
val surfaceDimDark = Color(0xFF131318)
val surfaceBrightDark = Color(0xFF39393F)
val surfaceContainerLowestDark = Color(0xFF0E0E13)
val surfaceContainerLowDark = Color(0xFF1B1B21)
val surfaceContainerDark = Color(0xFF1F1F25)
val surfaceContainerHighDark = Color(0xFF2A292F)
val surfaceContainerHighestDark = Color(0xFF35343A)

val Purple80 = Color(0xFFD0BCFF)
val BoxColor = Color(0xfff3f3f3)
val Star = Color(0xFFFF9800)
val GreenColor=Color(0xFF4CAF50)




*/